<?php
echo '      '
        . '<div class="modal fade" id="newUs" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">'
        . ' <div class="modal-dialog" role="document">'
        . '  <div class="modal-content">'
        . '   <div class="modal-header">'
        . '     <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>'
        . '     <h4 class="modal-title" id="myModalLabel">Nuevo usuario</h4>'
        . ''
        . ''
        . ''
        . ''
        . '   </div>'
        . '  </div>'
        . ' </div>'
        . '</div>';